[tox]
minversion = 4.0
envlist = pypy3, py310, py311, py312, py313, ruff, mypy
isolated_build = True

[gh-actions]
python =
    pypy-3.10: pypy3
    3.10: py310, ruff, mypy
    3.11: py311
    3.12: py312
    3.13: py313

[testenv]
deps =
    pytest
    pytest-xdist
commands = pytest bgpy --basetemp={envtmpdir}

[testenv:mypy]
basepython = python3.11
deps = -r {toxinidir}/requirements_dev.txt
commands = mypy bgpy

[testenv:ruff]
basepython = python3.11
deps = ruff
commands =
    ruff check bgpy
    ruff format bgpy